Xatolar to'g'rilandi
JmlKhon/TestSchool pull request #11
Opened 2023-04-01 11:19 UTC by mrIminjonov

2023-04-01 18:46 UTC, isfandiyoro5 requested changes

2023-04-01 18:46 UTC, isfandiyoro5 commented on TestSchoolWebApi/Models/Dtos/AddressRequestDto.cs
> +        public string AddressId { get; set; }
AdressId kerak emas

2023-04-01 18:46 UTC, isfandiyoro5 commented on TestSchoolWebApi/Models/Dtos/AddressRequestDto.cs
> +        public string Region { get; set; }
Region Adress class da yoq lekin sen Dtoga qoshib qoyibsan

2023-04-01 18:46 UTC, isfandiyoro5 commented on TestSchoolWebApi/Models/Dtos/AddressResponseDto.cs
> +        public string City { get; set; }
Street ni ham qoshish kk

2023-04-03 09:10 UTC, mrIminjonov commented on TestSchoolWebApi/Models/Dtos/AddressRequestDto.cs
> +        public string AddressId { get; set; }
ok togrilemiz

2023-04-03 09:11 UTC, mrIminjonov commented on TestSchoolWebApi/Models/Dtos/AddressResponseDto.cs
> +        public string City { get; set; }
responseda streetni korsatishni istamadim sababi malumotlar ni deyarli hammasi ochiq bolib qoladi unda request bilan responseni farqi qomedi

2023-04-04 13:39 UTC, JmlKhon approved these changes

2023-04-04 13:41 UTC, isfandiyoro5 approved these changes

2023-04-04 13:41 UTC, merged