13 create dto for student model
JmlKhon/TestSchool pull request #12
Opened 2023-04-01 12:46 UTC by mrIminjonov

2023-04-01 18:56 UTC, isfandiyoro5 requested changes

2023-04-01 18:56 UTC, isfandiyoro5 commented on TestSchoolWebApi/Models/Dtos/AddressRequestDto.cs
> +﻿namespace TestSchool.Models.Dtos
Gofurjon hafa boma lekin bu joyda sen studentni branchiga yana adressni ham yuklab qoyibsan adresing ozi 14-barnchda edi shunchun sen buni ochirishing kk !

2023-04-01 18:56 UTC, isfandiyoro5 commented on TestSchoolWebApi/Models/Dtos/AddressResponseDto.cs
> +﻿namespace TestSchool.Models.Dtos
Buni ham ochirishing kerak

2023-04-01 18:56 UTC, isfandiyoro5 commented on TestSchoolWebApi/Models/Dtos/StudentRequestDto.cs
> +        public int StudentId { get; set; }
StudentId kerak emas requestda

2023-04-01 18:56 UTC, isfandiyoro5 commented on TestSchoolWebApi/Models/Dtos/StudentRequestDto.cs
> +        public string Email { get; set; }
Email ortqicha

2023-04-01 18:56 UTC, isfandiyoro5 commented on TestSchoolWebApi/Models/Dtos/StudentRequestDto.cs
> +        public string Phone { get; set; }
Phone ham kerak emas

2023-04-01 18:56 UTC, isfandiyoro5 commented on TestSchoolWebApi/Models/Dtos/StudentResponseDto.cs
> +        public int StudentName { get; set; }
StudentLastName  qoshish kerak

2023-04-01 18:56 UTC, isfandiyoro5 commented on TestSchoolWebApi/Models/Dtos/StudentResponseDto.cs
> +        public int StudentName { get; set; }
FirstName yoz nameni orniga 
lekin hafa bop ketmagin a  buni bitta menmas boshqalar bn tekshirdik !
agar StudentName yozmoqchi boseng uni avtomapperda qilish kk lekin uni bekzod aka qiladi

2023-04-03 06:00 UTC, JmlKhon commented on TestSchoolWebApi/Models/Dtos/StudentRequestDto.cs
> +        public string Email { get; set; }
email bolishi kerak requestda @isfandiyoro5

2023-04-03 06:00 UTC, JmlKhon commented on TestSchoolWebApi/Models/Dtos/StudentRequestDto.cs
> +        public string Phone { get; set; }
Phone ham qolishi kerak

2023-04-03 06:01 UTC, JmlKhon commented on TestSchoolWebApi/Models/Dtos/StudentResponseDto.cs
> +        public int StudentName { get; set; }
response ga lastname bilan firstname ni qoshib StudentName qilsak boladi

2023-04-03 06:02 UTC, JmlKhon commented on TestSchoolWebApi/Models/Dtos/StudentResponseDto.cs
> +        public int StudentName { get; set; }
StudentName  qoladi

2023-04-04 13:46 UTC, isfandiyoro5 approved these changes, later dismissed

2023-04-04 15:18 UTC, closed without merging